alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car_Person drop constraint FKe1f9w707g98j95ompn85lveeg;
alter table Car_Person drop constraint FK6ddvravcngtfdlpe6gwe4untu;
drop table Car;
drop table Car_Person;
drop table Person;
alter table Car drop constraint FK86rkldg35bxikmwrqs7yn18cg;
drop table Car;
drop table Person
